apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
  name: nginx
  namespace: default
spec:
  ports:
  - port: 8036
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx
  type: ClusterIP
